import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ geolocation: { latitude: -34.9058, longitude: -56.1882 }, permissions: ["geolocation"] });
const p = await ctx.newPage();
const errs=[]; p.on("pageerror",e=>errs.push(e.message.slice(0,100)));
await p.setViewportSize({ width: 390, height: 844 });
await p.goto("http://localhost:3000/", { waitUntil: "networkidle", timeout: 60000 }).catch(()=>{});
await p.waitForTimeout(1500);
await p.locator('button[aria-label="Ajustes"]:visible').first().click({timeout:5000}).catch(()=>{});
await p.waitForTimeout(800);
await p.screenshot({ path: "D:/tmp/shots/settings-main.png" });
await p.locator('text=Cómo funciona Cuándo').first().click({timeout:4000}).catch(e=>console.log("nav cf fail",e.message.slice(0,50)));
await p.waitForTimeout(700);
await p.screenshot({ path: "D:/tmp/shots/settings-comofunciona.png" });
await p.locator('button[aria-label="Volver"]').first().click({timeout:3000}).catch(()=>{});
await p.waitForTimeout(500);
await p.locator('text=Política de Privacidad').first().click({timeout:4000}).catch(e=>console.log("nav fail",e.message.slice(0,50)));
await p.waitForTimeout(700);
await p.screenshot({ path: "D:/tmp/shots/settings-privacy.png" });
console.log("errors:", errs.length, errs.slice(0,3));
await b.close();
